### ISSUE TITLE
Contest undefined 请教

### ISSUE THREAD

**Issue by keac** [zhblue/vjudge#3]
在problem中题目显示正常
Contest 显示 undefined 前端报错
script.min.js?1550386801304:952 Uncaught TypeError: Cannot read property 'undefined' of undefined
    at t (script.min.js?1550386801304:952)
    at b (script.min.js?1550386801304:932)
    at script.min.js?1550386801304:973
    at dispatch (script.min.js?1550386801304:88)
    at D.handle (script.min.js?1550386801304:82)
    at Object.trigger (script.min.js?1550386801304:86)
    at script.min.js?1550386801304:98
    at Function.each (script.min.js?1550386801304:20)
    at l.fn.init.each (script.min.js?1550386801304:16)
    at l.fn.init.trigger (script.min.js?1550386801304:98)

**Comment by keac** [comment]
/var/log/tomcat?/catalina.out 报错

Caused by: java.lang.Error: Unresolved compilation problem: 
	The method getLanguages(String, String) in the type LanguageManager is not applicable for the arguments (String)

	at judge.action.ContestAction.showProblem(ContestAction.java:647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:892)
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1294)
	... 90 more
/-- Encapsulated exception ------------\
java.lang.Error: Unresolved compilation problem: 
	The method getLanguages(String, String) in the type LanguageManager is not applicable for the arguments (String)

**Comment by zhblue** [comment]
可能是没有更新完整，试试导入eclipse进行调试，自行打包war
